
/**:
  ros__parameters:
    frame_id: 'world'

    primary:
      urdf_path: 'config/prism_workpiece.urdf'
      transform:
        translation:
          x: 1.2
          y: 0.0
          z: 0.125
        rotation:
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0

    gripper:
      urdf_path: 'config/test_gripper.urdf'
      max_opening: 0.36

    secondaries:
      - id: 'ground_plane'
        type: 'ground_plane'
        size_x: 4.0
        size_y: 4.0
        z_position: 0.0

    sampling:
      min_angle_deg: 160.0
      max_angle_deg: 180.0

      min_gripper_opening: 0.06
      max_gripper_opening: 0.36

      sample_density: 0.01

      normal_sample_density: 1.0
      max_lateral_deviation: 0.03
      alignment_threshold: 0.95

    orientation:
      finger_length: 0.2
      finger_radius: 0.02

      max_edge_candidates: 5
      dual_seed_dedup_tolerance_deg: 3.0
      max_edges_per_contact: 0

      angle_offsets: [-15.0, 0.0, 15.0]

      stop_on_first_valid: false
      collision_tolerance: 0.001
      debug_full_sweep: false
      debug_sweep_step_deg: 10.0

      randomize_seeds: true

    kissing:
      contact_threshold: 0.8
      collision_tolerance: 0.001

    fcl:
      enabled: true
      triangulation_deflection: 0.001



    output:
      max_grasps: 50
      min_quality: 0.0
