/**:
  ros__parameters:
    base_link:
      urdf_path: 'urdf/environment/workpiece.urdf.xacro'
      id: 'base_link'
      spawn_name: 'base_link'
      pose:
        x: 1.2
        y: -0.5
        z: 0.65
      orientation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0

    child_link:
      urdf_path: 'urdf/environment/prism.urdf.xacro'
      id: 'child_link'
      spawn_name: 'child_link'
      pose:
        x: 1.2
        y: 0.0
        z: 0.125
      orientation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0

    frame_id: 'world'