# Test 4: T-joint 45° rotation (around Y-axis)
/**:
  ros__parameters:
    base_link:
      urdf_path: 'urdf/environment/workpiece.urdf.xacro'
      id: 'base_link'
      spawn_name: 'workpiece_tjoint_45deg'
      pose:
        x: 1.2
        y: -0.5
        z: 0.65
      orientation:
        x: 0.0
        y: 0.3826834
        z: 0.0
        w: 0.9238795
      
    child_link:
      urdf_path: 'urdf/environment/cube.urdf.xacro'
      id: 'child_link'
      spawn_name: 'cube_tjoint_45deg'
      pose:
        x: 1.2
        y: -0.5
        z: 0.125
      end_pose:
        position:
          x: 1.394
          y: -0.5
          z: 0.844
        orientation:
          x: 0.0
          y: 0.3826834
          z: 0.0
          w: 0.9238795
    
    frame_id: 'world'