/**:
  ros__parameters:
    base_link:
      urdf_path: 'urdf/environment/prism.urdf.xacro'
      id: 'base_link'
      spawn_name: 'main_prism'
      pose:
        x: 1.2
        y: -0.9
        z: 0.65
      orientation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0

    child_link:
      urdf_path: 'urdf/environment/prism.urdf.xacro'
      id: 'child_link'
      spawn_name: 'secondary_prism'
      pose:
        x: 1.2
        y: -0.1
        z: 0.65
      end_pose:
        position:
          x: 1.2
          y: -0.1
          z: 0.65
        orientation:
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0

    frame_id: 'world'
